[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "icechunk"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

dependencies = ["zarr==3.0.0a7"]

[tool.poetry]
name = "icechunk"
version = "0.1.0"
description = "Icechunk Python"
authors = ["Earthmover <info@earthmover.io>"]
readme = "README.md"
packages = [
    { include = "icechunk", from = "python" }
]

[project.optional-dependencies]
test = [
  "coverage",
  "mypy",
  "object-store-python",
  "pytest",
  "pytest-cov",
  "pytest-asyncio",
  "ruff",
  "dask",
  "distributed",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "icechunk._icechunk_python"
python-source = "python"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.pyright]
venvPath = "."
venv = ".venv"
